services:
  pwsafe:
    build: .
    ports:
      # Change first number to use a different host port
      - "8080:8080"
    volumes:
      # User-provided data
      - /opt/pwsafe/config:/config:ro
      # Service-managed data
      - /opt/pwsafe/data:/data
    restart: unless-stopped
